version: '3.2'
services:
  drone-server:
    container_name: v-drone-server
    image: drone/drone:latest
    ports:
      - 4000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/drone:/var/lib/drone/
    restart: always
    command: apk add --no-cache tzdata
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone.iamsee.com:2544
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      #- DRONE_GOGS=true
      #- DRONE_GOGS_SKIP_VERIFY=false
      #- DRONE_GOGS_SERVER=http://gogs:3000
      #- DRONE_PROVIDER=gogs
      - DRONE_GITHUB_SERVER=https://github.com 
      - DRONE_GITHUB_CLIENT_ID=c8597cfa6de3a4236878
      - DRONE_GITHUB_CLIENT_SECRET=e60565dbc9e0a70390817dbf3be2065e8d6bc5de
      # - DRONE_GITHUB_SERVER=https://gitee.com 
      # - DRONE_GITHUB_CLIENT_ID=462e5673d9814da03e103601c7723750f32c636926977410a3a57c9dc457c24a
      # - DRONE_GITHUB_CLIENT_SECRET=547f783e13125fb2a4a27324047735e14a8a9cca11ab8a9cb54ef885d370bfb2
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:alic,admin:true
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      #- DRONE_DATABASE_DATASOURCE=root:zhuotong@tcp(bytelurk.com:3306)/drone?parseTime=true
      #- DRONE_DATABASE_DRIVER=mysql
      - TZ=Asia/Shanghai
  frp:
        image: cloverzrg/frps-docker
        restart: always
        container_name: v-frp
        ports:
                - 7000:7000
                - 7001:7001
                - 7080:80
                - 7443:443
                - 7500:7500
                - 7022:7022
                - 7300-7400:7300-7400
                - 3001:3001 #监听端口
                - 81:81  # nas外网端口 

        volumes:
                - $PWD/frp/conf:/conf

