version: '3.2'
services:
  nginx:
      container_name: v-nginx
      image: nginx:latest
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
        - $PWD/nginx/vhost:/etc/nginx/conf.d
        - $PWD/nginx/logs/:/usr/share/nginx/logs/
        - $PWD/nginx/cert/:/etc/cert/
        - $PWD/www/:/usr/share/nginx/html/
        - /etc/v2ray/:/etc/v2ray/
        
      links:
        - drone-server:drone-server
        - v2ray:v2ray
        - owncloud:owncloud
       # - filebrowser:filebrowser
      depends_on:
        - drone-server
        - v2ray
        - owncloud
        - filebrowser
  php:
      image: iamsee/php-fpm:7.2
      ports:
       - "9000:9000"
      volumes:
        - $PWD/php/php.ini:/usr/local/etc/php.ini
        - $PWD/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - $PWD/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - $PWD/php/logs:/var/log/php
        - $PWD/www/:/usr/share/nginx/html/
      links:
        - mysql:mysql
      depends_on:
        - mysql
      restart: always
      container_name: v-php
  mysql:
      image: mariadb:latest
      ports:
        - "3306:3306"
      volumes:
        - $PWD/mysql/data:/var/lib/mysql/
        - $PWD/mysql/my.cnf:/etc/mysql/my.cnf
        - $PWD/mysql/log:/var/log/mysql/
      environment:
            - MYSQL_ROOT_PASSWORD=zhuotong
      restart: always
      container_name: v-mysql
  drone-server:
    container_name: v-drone-server
    image: drone/drone:latest
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/drone:/var/lib/drone/
    restart: always
    command: apk add --no-cache tzdata
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone.bytelurk.com
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      #- DRONE_GOGS=true
      #- DRONE_GOGS_SKIP_VERIFY=false
      #- DRONE_GOGS_SERVER=http://gogs:3000
      #- DRONE_PROVIDER=gogs
      - DRONE_GITHUB_SERVER=https://github.com 
      - DRONE_GITHUB_CLIENT_ID=c8597cfa6de3a4236878
      - DRONE_GITHUB_CLIENT_SECRET=e60565dbc9e0a70390817dbf3be2065e8d6bc5de
      # - DRONE_GITHUB_SERVER=https://gitee.com 
      # - DRONE_GITHUB_CLIENT_ID=462e5673d9814da03e103601c7723750f32c636926977410a3a57c9dc457c24a
      # - DRONE_GITHUB_CLIENT_SECRET=547f783e13125fb2a4a27324047735e14a8a9cca11ab8a9cb54ef885d370bfb2
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:alic,admin:true
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      #- DRONE_DATABASE_DATASOURCE=root:zhuotong@tcp(bytelurk.com:3306)/drone?parseTime=true
      #- DRONE_DATABASE_DRIVER=mysql
      - TZ=Asia/Shanghai
  v2ray:
      container_name: v-v2ray
      image: wangyi2005/v2ray
      #ports:
      #  - 9080:8080
      environment:
        - VER=4.19.1
      volumes:
        - $PWD/v2ray/config.json:/config.json
        - $PWD/v2ray/entrypoint.sh:/entrypoint.sh
      #  - $PWD/v2ray/entrypoint.sh /entrypoint.sh
  owncloud:
      container_name: v-owncloud
      image: owncloud
      ports:
        - 9081:80
      volumes:
        - $PWD/www/owncloud:/var/www/html     
  filebrowser:
      container_name: v-filebrowser
      image: filebrowser/filebrowser
      ports:
        - 9100:80
      volumes:
        - /googleDriver:/srv
  ai_image:
      image: node:10
      working_dir: "/var/www/mobile-site"
      environment:
        - HOST=0.0.0.0
        - NODE_ENV=production
      volumes:
        - $PWD/www:/var/www/
      ports:
        - 3100:3100
      command: bash -c "npm start > server.log"
      container_name: v-ai_image
  frp:
        image: cloverzrg/frps-docker
        restart: always
        container_name: v-frp
        ports:
                - 7000:7000
                - 7001:7001
                - 7080:80
                - 7443:443
                - 7500:7500
                - 7022:7022
                - 7300-7400:7300-7400
                
        volumes:
                - $PWD/frp/conf:/conf

